### ISSUE TITLE
Shell error in antismash_overview_gather rule: Argument list too long

### ISSUE THREAD

**Issue by OmkarSaMo** [NBChub/bgcflow#229]
In a large project with close to 70 k BGCs the following issue appeared as the argument list for shell command was too long.

`/datadrive/data2/bgcflow/.snakemake/shell_tmp.pvmw0yn0/script.sh: line 2: /datadrive/data2/bgcflow/.snakemake/conda/18ddcd54edd3f107fecb89d7a50d830f_/bin/python: Argument list too long
`

**Comment by OmkarSaMo** [comment]
@matinnuhamunada - is this issue easy to resolve? It's very important to find some solution in large-scale run. Do you have temporary solution as well?

**Comment by matinnuhamunada** [comment]
Can you check if [15879d9](https://github.com/NBChub/bgcflow/pull/254/commits/15879d9d41140881d4697306a888ac9b5402b1ab) fixes the problem?

> Bash scripts written "safely" avoid any command $LONG_ARGUMENT_LIST, and instead use pipes when the argument list is unbounded, e.g. with constructs such as echo $LONG_ARGUMENT_LIST | xargs command. The latter works safely because echo is a bash "builtin", so no external command is run and the ARG_MAX limit is not relevant.

Inspired from:
https://github.com/snakemake/snakemake/issues/854

**Comment by OmkarSaMo** [comment]
@matinnuhamunada  - Still got an error on the large dataset with v0.7.0

`/datadrive/bgcflow/.snakemake/shell_tmp.41z66epq/script.sh: line 2: /datadrive/bgcflow/.snakemake/conda/5278299a2f85ccdaa9384b194969e4bd_/bin/python: Argument list too long
`

**Comment by matinnuhamunada** [comment]
Fix in https://github.com/NBChub/bgcflow/pull/258/commits/144ad89580dbf93fe331e341039161ddb8954536

**Comment by OmkarSaMo** [comment]
Thanks a lot for the fix
