### ISSUE TITLE
Error in Generating ARTS Notebook and in Serving the Results in MKdown and Metabase - branch 0.6.1

### ISSUE THREAD

**Issue by andrekind17** [NBChub/bgcflow#238]
Hi Matin,
I made a clean re-run on the example dataset with the bgcflow 0.6.1 version, just to make sure that there was no conflict among data. Except for deeptfactor (I posted a comment on the already opened issue), all the rules work.

Anyway, getting to the exploration of the results, I found a few problems: when running "bgcflow run --snakefile workflow/Report", it seems like if it does not find the needed files for generating the arts notebook. Actually the .ipynb file gets built, but the .md does not. 
At the end of the whole job I also get the following error "34 of 36 steps (94%) done. Exiting because a job execution failed.". Probably the whole job gets compromised by the arts notebook generation failure? In fact, when I serve with "bgcflow serve --project Lactobacillus_delbrueckii" the webpage does not show any figure for any of the existing jobs.
The visualization with jupyter lab is fine so far. 
On Metabase, instead, the sections "Raw Cdss" and "Raw Regions" do not display any data.

I will go on with running bgcflow on my data. Then I will start exploring, let me know when you have fixes.

 See below for arts notebook error message and see full attached log for details.

Activating conda environment: .snakemake/conda/03517672abe9c665423eb3b1c199390f_
[Fri Apr 21 15:12:12 2023]
Error in rule mkdocs_py_report:
    jobid: 24
    input: data/processed/Lactobacillus_delbrueckii/docs/arts.ipynb
    output: data/processed/Lactobacillus_delbrueckii/docs/arts.md
    log: workflow/report/logs/report/arts-report-Lactobacillus_delbrueckii.log (check log file(s) for error details)
    conda-env: /bigdata/home/WIN.DTU.DK/gentile/bgcflow/.snakemake/conda/03517672abe9c665423eb3b1c199390f_
    shell:
        
            jupyter nbconvert --to notebook --execute data/processed/Lactobacillus_delbrueckii/docs/arts.ipynb --output arts.ipynb 2>> workflow/report/logs/report/arts-report-Lactobacillus_delbrueckii.log
            jupyter nbconvert --to markdown data/processed/Lactobacillus_delbrueckii/docs/arts.ipynb --no-input --output arts.md 2>> workflow/report/logs/report/arts-report-Lactobacillus_delbrueckii.log
            
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
[arts-report-Lactobacillus_delbrueckii.log](https://github.com/NBChub/bgcflow/files/11296755/arts-report-Lactobacillus_delbrueckii.log)

**Comment by Androx0** [comment]
Thanks to last Matin implementations the error in "rule copy_readme" has been solved, but the error in "rule mkdocs_py_report" still remains and the prokka.md does not get generated.
Moreover, while visualizing the results through MkDocs report, the reports for bigslice, query-bigslice, eggnog, cblaster-genome and cblaster-bgc do not show any results. The roary report, instead, is not displayed at all, and the following error arises while serving the project:

INFO     -  [macros] - ERROR # _Macro Rendering Error_                                                                                                        
                                                                                                                                                              
            **UndefinedError**: 'dict object' has no attribute 'roary'                                                                                        
                                                                                                                                                              
                                                                                                                                                              
            ```                                                                                                                                               
            Traceback (most recent call last):                                                                                                                
              File "/bigdata/home/WIN.DTU.DK/gentile/mambaforge/envs/bgcflow/lib/python3.11/site-packages/mkdocs_macros/plugin.py", line 480, in render       
                return md_template.render(**page_variables)                                                                                                   
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                   
              File "/bigdata/home/WIN.DTU.DK/gentile/mambaforge/envs/bgcflow/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render        
                self.environment.handle_exception()                                                                                                           
              File "/bigdata/home/WIN.DTU.DK/gentile/mambaforge/envs/bgcflow/lib/python3.11/site-packages/jinja2/environment.py", line 936, in                
            handle_exception                                                                                                                                
                raise rewrite_traceback_stack(source=source)
              File "<template>", line 195, in top-level template code
              File "/bigdata/home/WIN.DTU.DK/gentile/mambaforge/envs/bgcflow/lib/python3.11/site-packages/jinja2/environment.py", line 466, in getitem
                return obj[argument]
                       ~~~^^^^^^^^^^
            jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'roary'

**Comment by Androx0** [comment]
I confirm that the error in "rule mkdocs_py_report" has been solved and prokka.md gets generated. Also the roary report now gets generated (the problem was due to the project_metadata.json not being updated).

These problems remain:

- As regarding Metabase, if you close the connection with ctrl-c and then open it again, it will ask you the set-up the account and the databases all over again.

- While visualizing BGCflow results through MkDocs report, the reports for bigslice, query-bigslice, eggnog, cblaster-genome and cblaster-bgc do not show any results.
