### ISSUE TITLE
Error in Rule Roary_Out on Personal Dataset - branch 0.6.1

### ISSUE THREAD

**Issue by Androx0** [NBChub/bgcflow#239]
Hi, I runned roary on the example dataset and it was successful. On my personal dataset, instead, I get this error for roary out (find attached the specific log. It seems the pan_genome_reference.fa file cannot be located):
[roary-out-Actinoallomurus_86_Genomes.log](https://github.com/NBChub/bgcflow/files/11336457/roary-out-Actinoallomurus_86_Genomes.log)

Activating conda environment: .snakemake/conda/784396d771d3e2189839e7baa154b27d_
[Wed Apr 26 19:26:37 2023]
Finished job 1236.
1 of 4 steps (25%) done
Select jobs to execute...

[Wed Apr 26 19:26:39 2023]
rule roary_out:
    input: data/interim/roary/Actinoallomurus_86_Genomes, data/processed/Actinoallomurus_86_Genomes/automlst_wrapper
    output: data/processed/Actinoallomurus_86_Genomes/roary, data/processed/Actinoallomurus_86_Genomes/roary/df_gene_presence_binary.csv
    log: workflow/report/logs/roary/roary-out-Actinoallomurus_86_Genomes.log
    jobid: 1235
    reason: Missing output files: data/processed/Actinoallomurus_86_Genomes/roary/df_gene_presence_binary.csv; Input files updated by another job: data/interim/roary/Actinoallomurus_86_Genomes
    wildcards: name=Actinoallomurus_86_Genomes
    resources: tmpdir=/tmp

Activating conda environment: .snakemake/conda/03517672abe9c665423eb3b1c199390f_
[Wed Apr 26 19:26:54 2023]
Error in rule roary_out:
    jobid: 1235
    input: data/interim/roary/Actinoallomurus_86_Genomes, data/processed/Actinoallomurus_86_Genomes/automlst_wrapper
    output: data/processed/Actinoallomurus_86_Genomes/roary, data/processed/Actinoallomurus_86_Genomes/roary/df_gene_presence_binary.csv
    log: workflow/report/logs/roary/roary-out-Actinoallomurus_86_Genomes.log (check log file(s) for error details)
    conda-env: /bigdata/home/WIN.DTU.DK/gentile/bgcflow/.snakemake/conda/03517672abe9c665423eb3b1c199390f_
    shell:
        
        python workflow/bgcflow/bgcflow/data/make_pangenome_dataset.py data/interim/roary/Actinoallomurus_86_Genomes data/processed/Actinoallomurus_86_Genomes/roary data/processed/Actinoallomurus_86_Genomes/automlst_wrapper 2>> workflow/report/logs/roary/roary-out-Actinoallomurus_86_Genomes.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by OmkarSaMo** [comment]
Hi @Androx0, I assume you tried to change the parameter here and that is enough.
https://github.com/NBChub/bgcflow/blob/b8afea678eb8d8fe44642dff4d1e320836ba3040/workflow/rules/roary.smk#L10

The job was done in prior run of the rule `roary` which created many of the important files and thus it will not be rerun by default. 

You will need to force rerun of the rule using snakemake. Alternatively, you can just delete the `data/interim/roary/Actinoallomurs_86` folder. Deleting this folder will inform snakemake that this rule also needs to be run.

Always try `bgcflow run -n` to see which rules are planned - and here you should get `roary` as well.

**Comment by Androx0** [comment]
Thanks, would you have a suggestion for the command to use to force the rerun using snakemake? Because deleting the data/interim/roary/Actinoallomurs_86 folder will make the job running again from the beginning and I would like to avoid that if it is possible

**Comment by Androx0** [comment]
Thanks, it worked!
