### ISSUE TITLE
Check the default threshold parameter of bigslice rule

### ISSUE THREAD

**Issue by OmkarSaMo** [NBChub/bgcflow#263]
I think the threshold for membership value in the latest bigslice versions should be in the range of 0 to 1.2 instead of 900. I assume the corresponding value should be 0.9 now as the default is 0.4.

https://github.com/NBChub/bgcflow/blob/1b1a5b1b3493eca50f75ecaf1e57566070870f9a/workflow/rules/bigslice.smk#L28

**Comment by matinnuhamunada** [comment]
Seems like BiG-SLICE added normalization too, which screws up the query to current BiG-FAM.
The query broke at this commit: https://github.com/medema-group/bigslice/commit/8be91acf2637c5a3e81f38036dceecd596966a5b

**Full Changelog**:  https://github.com/medema-group/bigslice/compare/08a56e..103d8f2
