### ISSUE TITLE
bgcflow build report - Failed

### ISSUE THREAD

**Issue by Tykyo** [NBChub/bgcflow#313]
Hello,

With version 0.8.0 or dev-0.8.1, the command 'bgcflow build report' failed. The fix was to edit the file workflow/bgcflow/bgcflow/data/get_project_metadata.py and changing line 76: 'name = project["name"]' to 'name = project.name'. 
Because the environment use python 3.9.x. It's working without modification if we run with python 3.11.x

The error was :

> Traceback (most recent call last):
  File "/home/user/test/bgcflow/workflow/bgcflow/bgcflow/data/get_project_metadata.py", line 132, in \<module>
    get_project_metadata(sys.argv[1], sys.argv[2], bgcflow_version=sys.argv[3])
  File "/home/user/test/bgcflow/workflow/bgcflow/bgcflow/data/get_project_metadata.py", line 124, in get_project_metadata
    all_metadata = get_all_metadata(config, rules_dict, BGCFlow_path, bgcflow_version)
  File "/home/user/test/bgcflow/workflow/bgcflow/bgcflow/data/get_project_metadata.py", line 76, in get_all_metadata
    name = project["name"]
  File "/home/user/test/bgcflow/.snakemake/conda/3deda062ddc053ac8c21f329e25c205c_/lib/python3.9/site-packages/peppy/project.py", line 1453, in \_\_getitem\_\_
    return self._project_data[item]
KeyError: 'name'

I hope this will be useful.

**Comment by matinnuhamunada** [comment]
Hi, thank you for the find :)
It seems this is caused by the latest update in the peppy [v0.40.0](https://github.com/pepkit/peppy/releases/tag/v0.40.0) which happens 4 days ago.

> [v0.40.0a1](https://github.com/pepkit/peppy/releases/tag/v0.40.0a1) Pre-release
First alpha release

>
> This version introduced backwards-incompatible changes.

>
> Replaced attmap with MutableMapping. (which resulted in the removal of the attribute functionality previously available in attmap)
> Replaced OrderedDict with dict.
> Deprecated support for Python versions <= 3.7.

For now I will pin the peppy version to [v0.35.7](https://github.com/pepkit/peppy/releases/tag/v0.35.7) as I need to make sure the backward incompatible changes does not affect other pep related scripts.

**Comment by Tykyo** [comment]
Hi, glad the solution was easy. Works perfectly now.
