### ISSUE TITLE
cblaster version, small error that has been fixed by cblaster in later versions

### ISSUE THREAD

**Issue by MatissMaleckis** [NBChub/bgcflow#315]
There is error when requesting followoing:
-b cblaster_output.csv -bde ',' -bkey max -bat identity

It is caused by an error in the cblaster script which they have already fixed but is part of current version 1.3.12. Patching to newer cblaster version should fix the error but require recreation of diamond databases that have been created with old version. This is rather fast process.

**Comment by matinnuhamunada** [comment]
Fixed in https://github.com/NBChub/bgcflow/releases/tag/v0.9.0
